baseURL = 'https://www.fresnescyclette.fr/'
defaultContentLanguage = 'fr'
languageCode = 'fr-fr'
title = 'FresnesCyclette'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "FresnesCyclette"
    homepage = "favicon.png"
    homepage_height = "192px"
    homepage_width = "192px"

  [params.homepage_meta_tags]
    meta_description = "FresnesCyclette - Atelier de co-réparation vélos à Fresnes"
    meta_og_title = "FresnesCyclette"
    meta_og_type = "website"
    meta_og_url = "https://www.fresnescyclette.fr"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Fresnescyclette - Atelier de co-réparation vélos à Fresnes"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
    name = "Mission"
    url = "/mission/"
    weight = 1

[[menu.main]]
	name = "Activités"
	url = "/services/"
    weight = 2

[[menu.main]]
    name = "Contactez-nous"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
